# Generated by Django 5.2.3 on 2025-06-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('notes', models.JSONField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, null=True)),
                ('consecutive', models.BooleanField(blank=True, null=True)),
                ('allow_mistakes', models.BooleanField(blank=True, null=True)),
                ('chord', models.BooleanField(blank=True, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='quizzes.quiz')),
            ],
        ),
    ]
