# Generated by Django 5.2.3 on 2025-07-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('play_piano', models.BooleanField(default=False)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('ordered', models.BooleanField(blank=True, null=True)),
                ('consecutive', models.BooleanField(blank=True, null=True)),
                ('allow_mistakes', models.BooleanField(blank=True, null=True)),
                ('chord', models.BooleanField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='courses.lesson')),
            ],
        ),
    ]
