# Generated by Django 5.2.3 on 2025-06-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_screen_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='screen',
        ),
        migrations.AddField(
            model_name='screen',
            name='allow_mistakes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='chord',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='consecutive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='ordered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
